services:
  db:
    #Version of postgres
    image: postgres:16
    environment: #in the first run dervice reads this env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notes_app
    healthcheck: #built-in mechanism chron to check db
      test: ["CMD-SHELL", "pg_isready -U app -d notes"] 
        #run cmd in container shell
        #pg_iseready=postgres utility, check if server accepts connections
      interval: 5s
      timeout: 3s
      retries: 10 #how may failes in a row to set status unhealthy
    ports:
      - "5432:5432" #port on my pc : port in container -> to reach it from outside
    volumes:
      - pgdata:/var/lib/postgresql/data #pddata lives separately from container

      # if there is no pgdata(means tables) - it goes to storage and creates table
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # [from where] : [to where= default folder which image checks first time in initialisation]

volumes:
  pgdata: #empty values means - use default



